{% set name = "watchgod" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29a1d8f25e1721ddb73981652ca318c47387ffb12ec4171ddd7b9d01540033b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - watchgod = watchgod.cli:cli


requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - anyio >=3.0.0,<4

test:
  imports:
    - watchgod
  commands:
    - watchgod -h

about:
  home: https://github.com/samuelcolvin/watchgod
  summary: Simple, modern file watching and code reload in python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
